/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tresenraya;

import javax.swing.JOptionPane;

/**
 *
 * @author Fhany
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    String[][] matriz=new String[4][4];
    int mejorfila, mejorcolumna;
  
    public Tablero() {
        initComponents();
        InicializarMatriz();
        NuevaPartida();
        this.setLocationRelativeTo(null);
        
        jButton1.setEnabled(false);
    }
    
    private void InicializarMatriz(){
        matriz[1][1]="-";
        matriz[1][2]="-";
        matriz[1][3]="-";
        matriz[2][1]="-";
        matriz[2][2]="-";
        matriz[2][3]="-";
        matriz[3][1]="-";
        matriz[3][2]="-";
        matriz[3][3]="-";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        compu = new javax.swing.JTextField();
        human = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        unodos = new javax.swing.JLabel();
        unotre = new javax.swing.JLabel();
        dosuno = new javax.swing.JLabel();
        dosdos = new javax.swing.JLabel();
        treuno = new javax.swing.JLabel();
        tredos = new javax.swing.JLabel();
        tretre = new javax.swing.JLabel();
        dostre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        IniciarJuego = new javax.swing.JButton();
        unouno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tres en raya");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Puntaje"));

        jLabel2.setText("Humano:");

        jLabel3.setText("Computadora:");

        compu.setEditable(false);
        compu.setText("0");
        compu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compuActionPerformed(evt);
            }
        });

        human.setEditable(false);
        human.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(human, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(compu)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(compu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(human, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Juego"));

        unodos.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        unodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unodos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        unodos.setName("unodos"); // NOI18N
        unodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unodosMouseClicked(evt);
            }
        });

        unotre.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        unotre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unotre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        unotre.setName("unotre"); // NOI18N
        unotre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unotreMouseClicked(evt);
            }
        });

        dosuno.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        dosuno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dosuno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dosuno.setName("dosuno"); // NOI18N
        dosuno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dosunoMouseClicked(evt);
            }
        });

        dosdos.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        dosdos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dosdos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dosdos.setName("dosdos"); // NOI18N
        dosdos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dosdosMouseClicked(evt);
            }
        });

        treuno.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        treuno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        treuno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        treuno.setName("treuno"); // NOI18N
        treuno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treunoMouseClicked(evt);
            }
        });

        tredos.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        tredos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tredos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tredos.setName("tredos"); // NOI18N
        tredos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tredosMouseClicked(evt);
            }
        });

        tretre.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        tretre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tretre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tretre.setName("tretre"); // NOI18N
        tretre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tretreMouseClicked(evt);
            }
        });

        dostre.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        dostre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dostre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dostre.setName("dostre"); // NOI18N
        dostre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dostreMouseClicked(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(treuno, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tredos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tretre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dosuno, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dosdos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dostre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(unodos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(unotre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(unodos, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(unotre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dosuno, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(dosdos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(dostre, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tredos, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(tretre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(treuno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        IniciarJuego.setText("Iniciar Juego");
        IniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarJuegoActionPerformed(evt);
            }
        });

        unouno.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        unouno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unouno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        unouno.setName("unouno"); // NOI18N
        unouno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                unounoMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unounoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unounoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unounoMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IniciarJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(unouno, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unouno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IniciarJuego)
                        .addGap(30, 30, 30)
                        .addComponent(Reset)
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unounoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unounoMouseClicked
        // TODO add your handling code here:
       
        
         if((this.unouno.getText().equals("")) &&(IniciarJuego.isSelected())){
            this.matriz[1][1]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(0, 1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        }
            
        
    }//GEN-LAST:event_unounoMouseClicked

    
    private void unounoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unounoMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_unounoMouseReleased

    private void unounoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unounoMouseEntered
        
     
    }//GEN-LAST:event_unounoMouseEntered

    private void unounoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unounoMouseExited
    
    }//GEN-LAST:event_unounoMouseExited

    private void unodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unodosMouseClicked
        // TODO add your handling code here:
      if((this.unodos.getText().equals("")) &&(IniciarJuego.isSelected())){
            this.matriz[1][2]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(0, 1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        }
        
      
    
    }//GEN-LAST:event_unodosMouseClicked

    private void unotreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unotreMouseClicked
        // TODO add your handling code here:
      
        
        if((this.unotre.getText().equals("")) &&(IniciarJuego.isSelected())){
            this.matriz[1][3]="X";
            impTablero();
            Maquina m=new Maquina();
            
            m.IniciaJ(0, 1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        }
    }//GEN-LAST:event_unotreMouseClicked

    private void dosunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosunoMouseClicked
        // TODO add your handling code here:
       
        if((this.dosuno.getText().equals(""))&&(IniciarJuego.isSelected())){
            this.matriz[2][1]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(0, 1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
          
            Evaluar(m);
        }
      
    }//GEN-LAST:event_dosunoMouseClicked

    private void dosdosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosdosMouseClicked
        // TODO add your handling code here:
        if((this.dosdos.getText().equals(""))  &&(IniciarJuego.isSelected())){
            this.matriz[2][2]="X";
            impTablero();
            Maquina m=new Maquina();
            
            m.IniciaJ(0, 1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
            
            Evaluar(m);
        }
      
    }//GEN-LAST:event_dosdosMouseClicked

    private void dostreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dostreMouseClicked
        // TODO add your handling code here:
       if((this.dostre.getText().equals(""))  &&(IniciarJuego.isSelected())){
            this.matriz[2][3]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(0, 1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        }
      
    }//GEN-LAST:event_dostreMouseClicked

    private void treunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treunoMouseClicked
        // TODO add your handling code here:
       if((this.treuno.getText().equals(""))  &&(IniciarJuego.isSelected())){
            this.matriz[3][1]="X";
            impTablero();
            Maquina m=new Maquina();
      
            m.IniciaJ(0, 1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
            
            Evaluar(m);
        }

    }//GEN-LAST:event_treunoMouseClicked

    private void tredosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tredosMouseClicked
        // TODO add your handling code here:
        if((this.tredos.getText().equals(""))  &&(IniciarJuego.isSelected())){
            this.matriz[3][2]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(0, 1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
         
            Evaluar(m);
        }
       
    }//GEN-LAST:event_tredosMouseClicked

    private void tretreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tretreMouseClicked
        // TODO add your handling code here:
        if((this.tretre.getText().equals("")) &&(IniciarJuego.isSelected())){
            this.matriz[3][3]="X";
            impTablero();
            Maquina m=new Maquina();
        
            m.IniciaJ(0, 1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        }
      
    }//GEN-LAST:event_tretreMouseClicked

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        InicializarMatriz();
        NuevaPartida();
        human.setText("0");
        compu.setText("0");
       
        
    }//GEN-LAST:event_ResetActionPerformed

    private void compuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compuActionPerformed

    
    // no puedo borrarlo T_T .. borre el boton pero no se borro el codigo ¬¬ ...
    private void comenzarjuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarjuegoActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_comenzarjuegoActionPerformed

    private void IniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarJuegoActionPerformed
        // TODO add your handling code here:
        NuevaPartida();
        InicializarMatriz();
        human.setText("0");
        compu.setText("0");
        
        jButton1.setEnabled(true);
       
    }//GEN-LAST:event_IniciarJuegoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void Evaluar(Maquina m){
        if(m.eval(this)==-1) {
                JOptionPane.showMessageDialog(this, "¡Ganaste! :D"); 
                NuevaPartida();
                InicializarMatriz();
                human.setText((Integer.parseInt(human.getText())+1)+"");
            }
            else if(m.eval(this)==1) {
                JOptionPane.showMessageDialog(this, "Perdiste... :( "); 
                NuevaPartida();
                InicializarMatriz();
                compu.setText((Integer.parseInt(compu.getText())+1)+"");
            }
            else if(m.eval(this)==0) {
                JOptionPane.showMessageDialog(this, "Empate :/"); 
                NuevaPartida();
                InicializarMatriz();
            }
    }
    public void NuevaPartida(){
        unouno.setText("");
        unodos.setText("");
        unotre.setText("");
        dosuno.setText("");
        dosdos.setText("");
        dostre.setText("");
        treuno.setText("");
        tredos.setText("");
        tretre.setText("");
    }
    public void impTablero(){
        if(!matriz[1][1].equals("-"))unouno.setText(matriz[1][1]);
        if(!matriz[1][2].equals("-"))unodos.setText(matriz[1][2]);
        if(!matriz[1][3].equals("-"))unotre.setText(matriz[1][3]);
        if(!matriz[2][1].equals("-"))dosuno.setText(matriz[2][1]);
        if(!matriz[2][2].equals("-"))dosdos.setText(matriz[2][2]);
        if(!matriz[2][3].equals("-"))dostre.setText(matriz[2][3]);
        if(!matriz[3][1].equals("-"))treuno.setText(matriz[3][1]);
        if(!matriz[3][2].equals("-"))tredos.setText(matriz[3][2]);
        if(!matriz[3][3].equals("-"))tretre.setText(matriz[3][3]);
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarJuego;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField compu;
    private javax.swing.JLabel dosdos;
    private javax.swing.JLabel dostre;
    private javax.swing.JLabel dosuno;
    private javax.swing.JTextField human;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel tredos;
    private javax.swing.JLabel tretre;
    private javax.swing.JLabel treuno;
    private javax.swing.JLabel unodos;
    private javax.swing.JLabel unotre;
    private javax.swing.JLabel unouno;
    // End of variables declaration//GEN-END:variables
}
