/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GATO;



import javax.swing.JOptionPane;

/**
 *
 * @author Fhany
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    String[][] matriz=new String[4][4];
    int mejorfila, mejorcolumna;
  
    public Tablero() {
        initComponents();
        InicializarMatriz();
        NuevaPartida();
        this.setLocationRelativeTo(null);
        
        
    }
    
    private void InicializarMatriz(){
        matriz[1][1]="-";
        matriz[1][2]="-";
        matriz[1][3]="-";
        matriz[2][1]="-";
        matriz[2][2]="-";
        matriz[2][3]="-";
        matriz[3][1]="-";
        matriz[3][2]="-";
        matriz[3][3]="-";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PuntajeHuman = new javax.swing.JLabel();
        PuntajePC = new javax.swing.JLabel();
        pc = new javax.swing.JTextField();
        human = new javax.swing.JTextField();
        ELGATO = new javax.swing.JPanel();
        unouno = new javax.swing.JButton();
        unodos = new javax.swing.JButton();
        unotres = new javax.swing.JButton();
        dosuno = new javax.swing.JButton();
        dosdos = new javax.swing.JButton();
        dostres = new javax.swing.JButton();
        tresuno = new javax.swing.JButton();
        tresdos = new javax.swing.JButton();
        trestres = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        IniciarJuego = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        fondoC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tres en raya");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Puntaje", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        PuntajeHuman.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PuntajeHuman.setText("Humano:");

        PuntajePC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PuntajePC.setText("Computadora:");

        pc.setEditable(false);
        pc.setBackground(new java.awt.Color(255, 255, 255));
        pc.setText("0");
        pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcActionPerformed(evt);
            }
        });

        human.setEditable(false);
        human.setBackground(new java.awt.Color(255, 255, 255));
        human.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PuntajePC)
                    .addComponent(PuntajeHuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(human, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(pc))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(human, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PuntajeHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PuntajePC))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 231, -1, 110));

        ELGATO.setBackground(new java.awt.Color(153, 204, 255));
        ELGATO.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        unouno.setBackground(new java.awt.Color(255, 255, 255));
        unouno.setToolTipText("");
        unouno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unounoActionPerformed(evt);
            }
        });

        unodos.setBackground(new java.awt.Color(255, 255, 255));
        unodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unodosActionPerformed(evt);
            }
        });

        unotres.setBackground(new java.awt.Color(255, 255, 255));
        unotres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unotresActionPerformed(evt);
            }
        });

        dosuno.setBackground(new java.awt.Color(255, 255, 255));
        dosuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosunoActionPerformed(evt);
            }
        });

        dosdos.setBackground(new java.awt.Color(255, 255, 255));
        dosdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosdosActionPerformed(evt);
            }
        });

        dostres.setBackground(new java.awt.Color(255, 255, 255));
        dostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dostresActionPerformed(evt);
            }
        });

        tresuno.setBackground(new java.awt.Color(255, 255, 255));
        tresuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresunoActionPerformed(evt);
            }
        });

        tresdos.setBackground(new java.awt.Color(255, 255, 255));
        tresdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresdosActionPerformed(evt);
            }
        });

        trestres.setBackground(new java.awt.Color(255, 255, 255));
        trestres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trestresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ELGATOLayout = new javax.swing.GroupLayout(ELGATO);
        ELGATO.setLayout(ELGATOLayout);
        ELGATOLayout.setHorizontalGroup(
            ELGATOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELGATOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ELGATOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ELGATOLayout.createSequentialGroup()
                        .addComponent(unouno, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(unodos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(unotres, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addGroup(ELGATOLayout.createSequentialGroup()
                        .addGroup(ELGATOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dosuno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tresuno, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ELGATOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dosdos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tresdos, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ELGATOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dostres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trestres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ELGATOLayout.setVerticalGroup(
            ELGATOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELGATOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ELGATOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unouno, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(unodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unotres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ELGATOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dosuno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dosdos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dostres, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ELGATOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tresuno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tresdos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trestres, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(ELGATO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        ELGATO.getAccessibleContext().setAccessibleName("EL GATO");

        Reset.setBackground(new java.awt.Color(255, 255, 255));
        Reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 154, -1));

        IniciarJuego.setBackground(new java.awt.Color(255, 255, 255));
        IniciarJuego.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        IniciarJuego.setText("Iniciar Juego");
        IniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 154, -1));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        titulo.setText("Tic Tac Gato ");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 180, 50));

        fondoC.setBackground(new java.awt.Color(0, 102, 102));
        fondoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GATO/fondo.jpg"))); // NOI18N
        fondoC.setText("Tic Tac Gato");
        fondoC.setOpaque(true);
        getContentPane().add(fondoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // BOTON RESET borra todo en tablero pero si perdiste/ganaste lo deja anotado en "puntuacion"
    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        
        InicializarMatriz();
        NuevaPartida();
        human.setText("0");
        pc.setText("0");
       
        
    }//GEN-LAST:event_ResetActionPerformed

    private void pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcActionPerformed

    
    // no puedo borrarlo T_T .. borre el boton pero no se borro el codigo ¬¬ ...
    private void comenzarjuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarjuegoActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_comenzarjuegoActionPerformed

//iniciar juego: puedes iniciar el juego aunque tengas casillas seleccionadas y no hayas terminado el juego, no te marca puntaje
    private void IniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarJuegoActionPerformed
      
        NuevaPartida();
        InicializarMatriz();
        human.setText("0");
        pc.setText("0");
    }//GEN-LAST:event_IniciarJuegoActionPerformed

   
    

// botones/casillas X y O TABLERO ---------------------------------------------
    
    private void unounoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unounoActionPerformed
            
        
           if((this.unouno.getText().equals(""))){
            this.matriz[1][1]= "X";
 
 
            impTablero();
            Maquina m=new Maquina();
            m.IniciaJ(1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();

            Evaluar(m);
        }
   
    }//GEN-LAST:event_unounoActionPerformed

    private void unodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unodosActionPerformed
       
        if((this.unodos.getText().equals(""))){
            this.matriz[1][2]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        }
   
    }//GEN-LAST:event_unodosActionPerformed

    private void unotresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unotresActionPerformed
    
        if((this.unotres.getText().equals(""))){
            this.matriz[1][3]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
         }
    
    }//GEN-LAST:event_unotresActionPerformed

    private void dosunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosunoActionPerformed

        
         if((this.dosuno.getText().equals(""))){
            this.matriz[2][1]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        
        
         }
        
        
    }//GEN-LAST:event_dosunoActionPerformed

    private void dosdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosdosActionPerformed
       
        
         if((this.dosdos.getText().equals(""))){
            this.matriz[2][2]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        
        } 
        
    }//GEN-LAST:event_dosdosActionPerformed

    private void dostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dostresActionPerformed
    
     if((this.dostres.getText().equals(""))){
            this.matriz[2][3]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        
     }
    }//GEN-LAST:event_dostresActionPerformed

    private void tresunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresunoActionPerformed

        
         if((this.tresuno.getText().equals(""))){
            this.matriz[3][1]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        }
    }//GEN-LAST:event_tresunoActionPerformed

    private void tresdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresdosActionPerformed
      
        
         if((this.tresdos.getText().equals(""))){
            this.matriz[3][2]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        }
    }//GEN-LAST:event_tresdosActionPerformed

    private void trestresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trestresActionPerformed
     
        
         if((this.trestres.getText().equals(""))){
            this.matriz[3][3]="X";
            impTablero();
            Maquina m=new Maquina();
           
            m.IniciaJ(1, this);
            this.matriz[this.mejorfila][this.mejorcolumna]="O";
            impTablero();
           
            Evaluar(m);
        
        }
         
         
         
    }//GEN-LAST:event_trestresActionPerformed
    public void Evaluar(Maquina m){
        if(m.eval(this)==-1) {
                JOptionPane.showMessageDialog(this, "¡Ganaste! :D"); 
                NuevaPartida();
                InicializarMatriz();
                human.setText((Integer.parseInt(human.getText())+1)+"");
            }
            else if(m.eval(this)==1) {
                JOptionPane.showMessageDialog(this, "Perdiste... :( "); 
                NuevaPartida();
                InicializarMatriz();
                pc.setText((Integer.parseInt(pc.getText())+1)+"");
            }
            else if(m.eval(this)==0) {
                JOptionPane.showMessageDialog(this, "Empate :/"); 
                NuevaPartida();
                InicializarMatriz();
            }
    }
    public void NuevaPartida(){
        unouno.setText("");
        unodos.setText("");
        unotres.setText("");
        dosuno.setText("");
        dosdos.setText("");
        dostres.setText("");
        tresuno.setText("");
        tresdos.setText("");
        trestres.setText("");
    }
    public void impTablero(){
        if(!matriz[1][1].equals("-"))unouno.setText(matriz[1][1]);
        if(!matriz[1][2].equals("-"))unodos.setText(matriz[1][2]);
        if(!matriz[1][3].equals("-"))unotres.setText(matriz[1][3]);
        if(!matriz[2][1].equals("-"))dosuno.setText(matriz[2][1]);
        if(!matriz[2][2].equals("-"))dosdos.setText(matriz[2][2]);
        if(!matriz[2][3].equals("-"))dostres.setText(matriz[2][3]);
        if(!matriz[3][1].equals("-"))tresuno.setText(matriz[3][1]);
        if(!matriz[3][2].equals("-"))tresdos.setText(matriz[3][2]);
        if(!matriz[3][3].equals("-"))trestres.setText(matriz[3][3]);
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ELGATO;
    private javax.swing.JButton IniciarJuego;
    private javax.swing.JLabel PuntajeHuman;
    private javax.swing.JLabel PuntajePC;
    private javax.swing.JButton Reset;
    private javax.swing.JButton dosdos;
    private javax.swing.JButton dostres;
    private javax.swing.JButton dosuno;
    private javax.swing.JLabel fondoC;
    private javax.swing.JTextField human;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pc;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton tresdos;
    private javax.swing.JButton trestres;
    private javax.swing.JButton tresuno;
    private javax.swing.JButton unodos;
    private javax.swing.JButton unotres;
    private javax.swing.JButton unouno;
    // End of variables declaration//GEN-END:variables
}
